# Generated by Django 6.1.1 on 2026-09-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("monument", "Monument"),
                            ("nature", "Nature"),
                            ("restaurant", "Restaurant"),
                            ("heritage", "Heritage"),
                            ("temple", "Temple"),
                            ("market", "Market"),
                            ("adventure", "Adventure"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("imphal", "Imphal"),
                            ("loktak", "Loktak"),
                            ("ukhrul", "Ukhrul"),
                            ("churachandpur", "Churachandpur"),
                            ("senapati", "Senapati"),
                            ("tamenglong", "Tamenglong"),
                            ("bishnupur", "Bishnupur"),
                            ("thoubal", "Thoubal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("short_description", models.CharField(max_length=280)),
                ("description", models.TextField(blank=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("address", models.CharField(blank=True, max_length=300)),
                ("rating", models.FloatField(default=0.0)),
                ("rating_count", models.IntegerField(default=0)),
                ("price_range", models.CharField(blank=True, max_length=20)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("opening_hours", models.CharField(blank=True, max_length=120)),
                ("contact", models.CharField(blank=True, max_length=60)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_featured", "-rating", "name"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="places_plac_categor_0dcb38_idx"
                    ),
                    models.Index(
                        fields=["region"], name="places_plac_region_a8a032_idx"
                    ),
                ],
            },
        ),
    ]
