# Generated by Django 6.0.3 on 2026-09-21 15:01

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("product", "Product"), ("service", "Service")],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(max_length=280)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_unit", models.CharField(max_length=30)),
                (
                    "images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[marketplace.models.validate_images],
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("imphal", "Imphal"),
                            ("loktak", "Loktak"),
                            ("ukhrul", "Ukhrul"),
                            ("churachandpur", "Churachandpur"),
                            ("senapati", "Senapati"),
                            ("tamenglong", "Tamenglong"),
                            ("bishnupur", "Bishnupur"),
                            ("thoubal", "Thoubal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("handicraft", "Handicraft"),
                            ("textile", "Textile"),
                            ("food", "Food"),
                            ("art", "Art"),
                            ("jewelry", "Jewelry"),
                            ("guide", "Guide"),
                            ("workshop", "Workshop"),
                            ("transport", "Transport"),
                            ("performance", "Performance"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_phone", models.CharField(max_length=40)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("whatsapp", models.CharField(blank=True, max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
