# Generated by Django 6.0.3 on 2026-09-21 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"role": "local"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketplace_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="marketplace.listing",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["type"], name="marketplace_type_63162f_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["region"], name="marketplace_region_8d408f_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["category"], name="marketplace_categor_c8d31d_idx"
            ),
        ),
    ]
