# Generated by Django 6.1.1 on 2026-09-21 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Homestay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("host_name", models.CharField(max_length=120)),
                ("host_phone", models.CharField(max_length=40)),
                ("host_email", models.EmailField(blank=True, max_length=254)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("imphal", "Imphal"),
                            ("loktak", "Loktak"),
                            ("ukhrul", "Ukhrul"),
                            ("churachandpur", "Churachandpur"),
                            ("senapati", "Senapati"),
                            ("tamenglong", "Tamenglong"),
                            ("bishnupur", "Bishnupur"),
                            ("thoubal", "Thoubal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=300)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("max_guests", models.IntegerField(default=2)),
                ("bedrooms", models.IntegerField(default=1)),
                ("beds", models.IntegerField(default=1)),
                ("bathrooms", models.IntegerField(default=1)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("images", models.JSONField(blank=True, default=list)),
                ("rating", models.FloatField(default=0.0)),
                ("rating_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-rating", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["region"], name="homestays_h_region_0cd24a_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="homestays_h_is_acti_75d9c2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_name", models.CharField(max_length=120)),
                ("guest_phone", models.CharField(max_length=40)),
                ("guest_email", models.EmailField(blank=True, max_length=254)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("guests", models.IntegerField(default=1)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "homestay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="homestays.homestay",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=120)),
                ("rating", models.IntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "homestay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="homestays.homestay",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
