# Generated by Django 6.0.3 on 2026-09-21 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("homestays", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="homestay",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homestays",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="homestay",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="homestays.homestay",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="homestay",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="homestays.homestay",
            ),
        ),
        migrations.AddIndex(
            model_name="homestay",
            index=models.Index(fields=["region"], name="homestays_h_region_0cd24a_idx"),
        ),
        migrations.AddIndex(
            model_name="homestay",
            index=models.Index(
                fields=["is_active"], name="homestays_h_is_acti_75d9c2_idx"
            ),
        ),
    ]
